# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
   
  commands:
    - pip install -r requirements.txt
    - mkdocs build
    - mkdir -p $READTHEDOCS_OUTPUT/html/  # Ensure HTML output directory exists
    - pip install -r requirements.txt      # Install project dependencies
    - mkdocs build --clean                 # Generate HTML documentation
    - cp -r site/* $READTHEDOCS_OUTPUT/html/  # Copy generated HTML files to output directory


mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: requirements.txt  # Adjust the path depending on your project structure
